/* 193. Dicionario de Dados */

-- USUARIO DO BANCO DE DADOS
SHOW USER;

-- TABELA DUMMY - IDIOTA, NELA NÃO TEM NADA
SELECT 1+1 AS SOMA FROM DUAL -- COLOCAR ALIAS SEMPRE

-- VERIFICANDO O AMBIENTE
-- B023 -> 32BITS
-- B047 -> 64BITS
SELECT METADATA FORM SYS.KOMPM$

-- DICIONARIO DE DADOS
SELECT * FROM DICT;

-- UNICA - RAC COMO SE FOSSE UM CLUSTER
-- EU ESTOU UTILIZANDO PARALELISMO?
SELECT PARALLEL FROM V$INSTANCE;

-- ESTRUTURAS DE MEMORIA
SELECT COMPONENT, CURRENT_SIZE, MIN_SIZE, MAX_SIZE
FROM V$SGA_DYNAMIC_COMPONENTES;

-- CONECTANDO A OUTRO BANCO DE DADOS
SQLPLUS SYSTEM/SENHA@NOMEBANCO
ORACLE_SID=BANCO01

--NOME DO BANCO DE DADOS
SELECT NAME FROM V$DATABASE;

-- VERSAO DO BANCO
SELECT BANNER FROM V$VERSION;

-- VERIFICAR PRIVILEGIOS DOS USUARIOS
SELECT * FROM USER_SYS_PRIVS;

--TABELAS DO USUARIO
SELECT TABLENAME FROM USER_TABLES;

/* ARMAZENAMENTO
LOGICO - TABLESPACES -> SEGMENTOS(OBJETOS) -> EXTENSOES (ESPAÇO) -> BLOCOS (DO SISTEMA OPERACIONAL)
FISICO - DATAFILES */

/* NÃO PODENMOS DETERMINAR EM QUAL ARQUIVO FISICO UM OBJETO FICARÁ. */

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY,
    NOME VARCHAR2(30),
    CARGA INT
) TABLESPACE USERS;

CREATE TABLE TESTE(
    IDTESTE INT,
    NOME VARCHAR2(30)
);

-- DICIONARIO DE DADO

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES;

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'CURSOS';

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'TESTE';

/* TODO OBJETO É CRIADO POR PADRAO NA TABLESPACE USERS
EXCETO QUANDO SE ESTA LOGADO COM O USUARIO SYSTEM - ENTAO
O OBJETO SERA CRIADO NA TABLESPACE SYSTEM */

SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME,
BYTES, BLOCKS, EXTENTS FROM USER_SEGMENTS
WHERE SEGMENT_NAME = 'CURSOS'

-- FORMATACAO DE COLUNAS

COLUMN TABLESPACE_NAME FORMAT A20;
COLUMN SEGMENT_NAME FORMAT A20;
COLUMN SEGMENT_TYPE FORMAT A20;


CREATE TABLESPACE RECURSOS_HUMANOS
DATAFILE 'E:\Oracle\DATA\RH_01.DBF'
SIZE 100M AUTOEXTEND
ON NEXT 100M
MAXSIZE 4096M;

ALTER TABLESPACE RECURSOS_HUMANOS
ADD DATAFILE 'E:\Oracle\DATA\RH_02.DBF'
SIZE 200M AUTOEXTEND
ON NEXT 200M
MAXSIZE 4096M;